src/MDivePlanner.Web/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using MDivePlanner.Domain.Entities;
using MDivePlanner.Domain.Interfaces;
using MDivePlanner.Web.App;
using MDivePlannerWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace MDivePlannerWeb.Controllers
{
    [Route("app")]
    public class AppController : Controller
    {
        private const string DiveResult = "DiveResult";

        private readonly IDiveCalculator _diveCalc;
        //private readonly IMemoryCache _memCache;
        private readonly DivesManager _divesManager;
        
        public AppController(IDiveCalculator diveCalculator, IMemoryCache memCache, DivesManager divesManager)
        {
            _diveCalc = diveCalculator;
            _divesManager = divesManager;
            //_memCache = memCache;

            ViewBag.DiveResult = "";
            ViewBag.DiveResultErrors = string.Empty;
        }

        [HttpGet("/")]
        public IActionResult Index()
        {
            _divesManager.StartSession();
            return View(new AppModel());
        }

        [HttpPost("/[controller]/calculate")]
        public IActionResult Calculate(DiveParamsModel model, [FromQuery] int? id = null)
        {
            model.IsModelValid = ModelState.IsValid;

            if (model.IsModelValid)
            {
                try
                {
                    var prevDive = _divesManager.GetPreviousDive(id);
                    var diveResult = _diveCalc.Calculate(prevDive, model.GetDiveParameters());
                    diveResult.DiveIndex = id.GetValueOrDefault();

                    var jsonSettings = new JsonSerializerSettings
                    {
                        Culture = new CultureInfo("en-US"),
                        ContractResolver = new CamelCasePropertyNamesContractResolver()                        
                    };

                    _divesManager.CurrentDive = diveResult;
                }
                catch (Exception ex)
                {
                    //TODO: notify client side
                    ViewBag.DiveResultErrors = ex.Message;
                    _divesManager.CurrentDive = null;
                    model.IsModelValid = false;
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return PartialView("DiveParams", model);
        }

        [HttpGet("/[controller]/newdive")]
        public IActionResult NewDive([FromQuery] bool? resetAll)
        {
            if (resetAll == true)
                _divesManager.ResetDives();

            _divesManager.CurrentDive = null;
            return PartialView("DiveParams", new DiveParamsModel().FillDefault());
        }

        [HttpGet("/[controller]/loaddive")]
        public IActionResult LoadDive([FromQuery] int id)
        {
            var dive = _divesManager.GetDive(id);
            return PartialView("DiveParams", new DiveParamsModel(dive.DiveParameters));
        }

        [HttpPost("/[controller]/dive")]
        public JsonResult SaveDive()
        {
            var divePlan = _divesManager.CurrentDive;
            if (divePlan != null)
            {
                _divesManager.CurrentDive = _divesManager.SaveDive(divePlan);
                return Json(new { diveName = divePlan.Description, diveId = divePlan.DiveIndex });
            }

            return Json(new { });
        }

        [HttpGet("/[controller]/result")]
        public JsonResult GetResult()
        {
            var currDive = _divesManager.CurrentDive;
            if (currDive != null)
                return Json(currDive);

            return Json(new { noData = true });
        }

        [HttpGet("/[controller]/text_result")]
        public JsonResult GetTextResult()
        {
            var currDive = _divesManager.CurrentDive;
            if (currDive != null)
            {
                var textResult = new DiveTextResult(currDive);
                return Json(textResult.Blocks);
            }

            return Json(new { noData = true });
        }

        [HttpGet("/[controller]/session")]
        public JsonResult SessionCheck()
        {
            return Json(new { newSession = !_divesManager.SessionExists() });
        }
    }
}

src/MDivePlanner.Web/Pages/Shared/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MDivePlannerWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MDivePlannerWeb.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/MDivePlanner.Web/Pages/Shared/Index.cshtml
@using MDivePlannerWeb.Models
@model AppModel

<div class="appRoot">
    <div class="appHeader">
        <div class="appNameContainer">
            <div class="appName">MDivePlanner</div>
            <div>Dive planner that implementes Bühlmann deco algorythm (ZHL-16a,b,c) with Gradient Factors</div>
        </div>
    </div>
    <div class="diveParams">
        <div class="blockLabel">
            <span>Dive Parameters</span>&nbsp;
            <span style="font-size: 12px">(depth - metters, time - minutes, volume - litters)</span>
        </div>
        <div>
            <form id="SubmitDiveParamsForm" asp-controller="App" asp-action="SetParams" method="post">
                <div id="DiveParamsContainer">
                    <partial name="DiveParams" model="Model.DiveParamsModel" />
                </div>
                <div class="buttonsPanel">
                    <div class="floatLeft">
                        <button id="SubmitDiveParams" class="button" type="button">Calculate</button>
                    </div>
                    <div class="floatRight" style="text-align: right">
                        <select id="SavedDives">
                            <option value="new-dive" selected="selected">New Dive</option>
                        </select>
                        <button id="SaveDive" class="button" type="button">Save Dive</button>
                        <button id="ResetDives" class="button" type="button">Reset Dives</button>
                    </div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>
    <div style="text-align: center;">
        <table class="result-table table1">
            <thead>
                <tr>
                    <td style="min-width: 360px">Dive Info</td>
                    <td>With Deco</td>
                    <td>Max ppO2</td>
                    <td>Consumed Gases</td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

        <table class="result-table table2">
            <thead>
                <tr>
                    <td>CNS</td>
                    <td>END</td>
                    <td>No Deco Time</td>
                    <td>Ascent Time</td>
                    <td>Full Desaturation</td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

        <div class="scale-container">
            <label>Scale: </label>
            <select id="GraphScale">
            </select>
        </div>

        <button id="GraphSwitch" style="position: absolute; top: -50px;">Gases</button>
        <canvas id="OutputCanvas" width="1024" height="650"></canvas>
        <div>
            <textarea id="TextResult" readonly="readonly" maxlength="99999999">
            </textarea>
        </div> 
    </div>
</div>

src/MDivePlanner.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MDivePlannerWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/app.css" />
</head>
<body>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <!--
    <script src="~/js/diveResult.js" asp-append-version="true"></script>
    <script src="~/js/utils.js" asp-append-version="true"></script>
    <script src="~/js/app.js" asp-append-version="true"></script>
    <script src="~/js/graph.js" asp-append-version="true"></script>
    -->
    <script src="~/js/appTypes.js" type="module" asp-append-version="true"></script>
    <script src="~/js/application.js" type="module" asp-append-version="true"></script>
    <script src="~/js/graph.js" type="module" asp-append-version="true"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>